# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nol2iNGhsE2kcb-3AS8a4mJ9Bg3cdTdy
"""

import pickle
import streamlit as st
from streamlit_option_menu import option_menu


# loading the saved models

audio_phish_model = pickle.load(open('audiophish.pkl', 'rb'))

#spoof_model = pickle.load(open('audiospoof.sav', 'rb'))

#email_model = pickle.load(open('email.sav', 'rb'))

# sidebar for navigation
with st.sidebar:
    selected = option_menu('Spoofing detection system',

                          ['Audio Phishing',
                           'Audio Spoofing',
                           'Email Phishing'],

                          icons=['music','audio','mail'],
                          default_index=0)


# Diabetes Prediction Page
if (selected == 'Audio Phishing'):

    # page title
    st.title('Audio Phishing detection')


    # getting the input data from the user
    col1 = st.columns(1)

    with col1:
        Transcripts = st.text_input('Call Transcript')


    # code for Prediction
    audio_phish_detection = ''

    # creating a button for Prediction

    if st.button('Diabetes Test Result'):
        prediction = audio_phish_model.predict(Transcripts)

        if (prediction[0] >= 0.5):
            phish_detection = 'phish'
        else:
            phish_detection = 'leg'

    st.success(audio_phish_detection)
